---
title: "Test on noisy matrices"
params:
  n_replicas: 10
  seed: 7050
---


## File of params
```{r}
library(jsonlite)
json_data <- fromJSON("params.json")

json_data$TestMatrix$rows <- unbox(300)
json_data$TestMatrix$cols <- unbox(300)
json_data$TestMatrix$decay <- unbox("slow")
json_data$TestMatrix$noise <- unbox(1.0)


json_data$RunParams$truncation_param <- unbox(10)

json_data$RunParams$seed <- unbox(params$seed)
```


## Varying the matrix dimension
Storing the result
```{r}
tested_SVDs <- c("rsi","rbki","exact")
```

```{r}
keys <- c("svd","replica","sigma")

performance_metrics <- c("exe_time",
                   "reconstruction_err")

test_results <- 
   data.frame(matrix(nrow=0,ncol=length(c(keys,performance_metrics))))
names(test_results) <- c(keys, performance_metrics)

test_results[] <- lapply(test_results, function(x) numeric())
test_results$svd <- character()
```

Actual computation
```{r}
library(dplyr)
library(Matrix)

for(curr_sigma in c(0,0.01,0.1)){
  for(replica_ind in 1:params$n_replicas){
    for(method in tested_SVDs){
      cat("SVD: ", method,"\n")
      #setting the method
      json_data$TestMatrix$noise <- unbox(curr_sigma)
      json_data$RunParams$method <- unbox(method)
      json_data$RunParams$seed <- unbox(params$seed + 4*replica_ind)
      write_json(json_data, "params.json", pretty = TRUE)
      
      system("/Users/marcogalliani/Desktop/fdaPDE-core/cmake-build-default/experiments/noisy-test/noisy_test")
      test_report <- read.csv(file="results/test_report.csv",header=F)
      
      #save results
      test_results <- test_results %>%
          add_row(svd=method, replica=replica_ind, sigma=curr_sigma)
      new_row <- test_results$svd==method & 
          test_results$replica==replica_ind &
          test_results$sigma==curr_sigma
      test_results[new_row, performance_metrics] <- unlist(test_report$V1)
    }
  }
}
```

# Saving results
```{r}
write.csv(format(test_results, digits = 16),
          paste("past-runs",
                paste("noisy-test",
                      ".csv",sep=""),
          sep="/")
)
```

## Visual
Colours
```{r}
col_palette <- palette.colors(n=4, palette = "R4")
color_map <- c(
  "rsi" = col_palette[2],
  "rbki" = col_palette[3],
  "exact" = col_palette[4]
)
```


```{r}
source("../r-utils/plot_utils.R")

test_results$sigma <- as.factor(test_results$sigma)

grouped_boxplot(test_results, "test",
                var_name.x = "sigma",var_name.y = "reconstruction_err",
                group_name = "svd",
                color_map = color_map, legend = T)
```


