---
title: "Plotting the results"
---

## File
```{r}
file_name <- paste("noisy-test",".csv",sep="")


library(readr)
test_results <- read_csv(paste("past-runs",file_name,sep="/"),
                         col_types = cols(...1 = col_skip()))

test_results[["svd"]] <- as.factor(test_results[["svd"]])
test_results[["sigma"]] <- as.factor(test_results[["sigma"]])
```

```{r}
plot_dir <- "plots/"
```


## Palette
```{r}
library(scales)
library(cowplot)
library(grid)
library(gridExtra) 
library(ggplot2)

col_palette <- palette.colors(n=4, palette = "R4")
color_map <- c(
  "rsi" = col_palette[2],
  "rbki" = col_palette[3],
  "exact" = col_palette[4]
)

dummy_plot <- 
  ggplot(data.frame(x = 1:length(color_map), y=1:length(color_map),
                  method=names(color_map)), 
       aes(x = x, y = y, color = method)) +
  geom_point(size = 5) +  # Use points just for the purpose of displaying the legend
  scale_color_manual(values = color_map) +  # Use the custom color mapping
  theme_void() +                            # Remove axes and background
  labs(color = "Method")


legend <- cowplot::get_legend(dummy_plot)
grid.newpage()
grid.draw(legend)

legend_grob <- grid.grabExpr(grid.draw(legend))

ggsave(paste(plot_dir,"legend-RandSVD-noisy",
             ".pdf", sep=""), 
       legend_grob, width = 2, height = 2)
```
## Results

### Accuracy
```{r}
rec_err.plot <- grouped_boxplot(test_results,
                 "Reconstruction error",
                 "sigma", "reconstruction_err",
                 group_name = "svd", color_map,
                 log.y = T
                 ) 

print(rec_err.plot)

ggsave(paste(plot_dir,
             "reconstruction_err",
             "-RandSVD-noisy",
             ".pdf", sep=""), 
       rec_err.plot, width = 10, height = 5)
```

```{r}
l_singVect_err.plot <- grouped_lineplot(rand_test,
                 "Error on the left singular vectors",
                 "size", "l_singVects_err",
                 group_name = "svd", color_map,
                 log.y = T
                 ) 

print(l_singVect_err.plot)

ggsave(paste(plot_dir,
             "l_singVects_err",
             "-RandSVD",
             "-rows", params$rows,
             "-cols", params$cols,
             ".pdf", sep=""), 
       l_singVect_err.plot, width = 10, height = 5)

```

```{r}
r_singVect_err.plot <- grouped_lineplot(rand_test,
                 "Error on the right singular vectors",
                 "size", "r_singVects_err",
                 group_name = "svd", color_map,
                 log.y = T
                 ) 

print(r_singVect_err.plot)

ggsave(paste(plot_dir,
             "r_singVects_err",
             "-RandSVD",
             "-rows", params$rows,
             "-cols", params$cols,
             ".pdf", sep=""), 
       r_singVect_err.plot, width = 10, height = 5)
```

```{r}
l_subspace_err.plot <- grouped_lineplot(rand_test,
                 "Left singular subspace error",
                 "size", "l_singVects_angle",
                 group_name = "svd", color_map,
                 log.y = T
                 ) 

print(l_subspace_err.plot)

ggsave(paste(plot_dir,
             "l_singSubspace_err",
             "-RandSVD",
             "-rows", params$rows,
             "-cols", params$cols,
             ".pdf", sep=""), 
       l_subspace_err.plot, width = 10, height = 5)
```
```{r}
r_subspace_err.plot <- grouped_lineplot(rand_test,
                 "Right singular subspace error",
                 "size", "r_singVects_angle",
                 group_name = "svd", color_map,
                 log.y = T
                 ) 

print(r_subspace_err.plot)

ggsave(paste(plot_dir,
             "r_singSubspace_err",
             "-RandSVD",
             "-rows", params$rows,
             "-cols", params$cols,
             ".pdf", sep=""), 
       r_subspace_err.plot, width = 10, height = 5)
```

```{r}
grouped_lineplot(subset(rand_test,svd!="rsi"),
                 "Singular value error",
                 "size", "singVal_err",
                 group_name = "svd", color_map,
                 log.y = T
                 ) 
```





