---
title: "Plotting the results"
params:
  n_cores: 1
  rows:
    value: "VAR"
    input: select
    choices: [1000,"VAR"]
  cols:
    value: 1000
    input: select
    choices: [1000,"VAR"]
---

## File
```{r}
file_name <- with(params, paste("RandSVD",
                                "-rows", params$rows,
                                "-cols", params$cols,
                                ".csv",sep=""))

if(params[["rows"]]=="VAR"){
  variable_dim <- "rows"
  fixed_dim <- "cols"
}else{
  variable_dim <- "cols"
  fixed_dim <- "rows"
}

library(readr)
test_results <- read_csv(paste("past-runs",file_name,sep="/"),
                         col_types = cols(...1 = col_skip()))

test_results[["svd"]] <- as.factor(test_results[["svd"]])
```

## Palette
```{r}
library(scales)
library(cowplot)
library(grid)
library(gridExtra) 
library(ggplot2)

col_palette <- hue_pal()(5)
color_map <- c(
  "exact" = col_palette[1],
  "rsi" = col_palette[2],
  "rbki" = col_palette[4]
  )

dummy_plot <- 
  ggplot(data.frame(x = 1:length(color_map), y=1:length(color_map),
                  method=names(color_map)), 
       aes(x = x, y = y, color = method)) +
  geom_point(size = 5) +  # Use points just for the purpose of displaying the legend
  scale_color_manual(values = color_map) +  # Use the custom color mapping
  theme_void() +                            # Remove axes and background
  labs(color = "Method")


legend <- cowplot::get_legend(dummy_plot)
grid.newpage()
grid.draw(legend)

legend_grob <- grid.grabExpr(grid.draw(legend))

ggsave(paste("plots/legend-RandSVD-rectangular",
             ".pdf", sep=""), 
       legend_grob, width = 2, height = 2)
```
## Results

### Execution times
- all
```{r}
source("plot_utils.R")

exeTimes.plt <- grouped_lineplot(test_results,
                 paste(fixed_dim,"= 1000,", variable_dim, "varying"),
                 "size", "exeTime",
                 group_name = "svd", color_map,
                 log.x=T,log.y=T,
                 complexity.lines=c(1/2,1,2)
                 )

print(exeTimes.plt)

ggsave(paste("plots/",
             "exeTime",
             "-RandSVD",
             "-rows", params$rows,
             "-cols", params$cols,
             ".pdf", sep=""), 
       exeTimes.plt, width = 10, height = 5)
```
- only randomized
```{r}
rand_test <- subset(test_results, svd %in% c("rsi","rbki"))

grouped_lineplot(rand_test,
                 paste(fixed_dim,"= 1000,", variable_dim, "varying"),
                 "size", "exeTime",
                 group_name = "svd", color_map,
                 log.x=T,log.y=T,
                 complexity.lines=c(1/2,1,2)
                 )
```
### Accuracy
```{r}
grouped_lineplot(rand_test,
                 paste(fixed_dim,"= 1000,", variable_dim, "varying"),
                 "size", "singValErr",
                 group_name = "svd", color_map
                 )
```

```{r}
grouped_lineplot(rand_test,
                 paste(fixed_dim,"= 1000,", variable_dim, "varying"),
                 "size", "l_singVecErr",
                 group_name = "svd", color_map
)
```

```{r}
grouped_lineplot(rand_test,
                 paste(fixed_dim,"= 1000,", variable_dim, "varying"),
                 "size", "r_singVecErr",
                 group_name = "svd", color_map
)
```


