---
title: "Experiments on SVD"
params:
  n_cores: 1
  rows:
    value: "VAR"
    input: select
    choice: [1000,"VAR"]
  cols:
    value: 1000
    input: select
    choice: [1000,"VAR"]
---

## File of params
```{r}
if(params[["rows"]]=="VAR"){
  variable_dim <- "rows"
  fixed_dim <- "cols"
}else {
  variable_dim <- "cols"
  fixed_dim <- "rows"
}
```

```{r}
library(jsonlite)
json_data <- fromJSON("params.json")

json_data$TestMatrix[[variable_dim]] <- unbox(1000)
json_data$TestMatrix[[fixed_dim]] <- unbox(1000)
json_data$TestMatrix$decay <- unbox("slow")

json_data$RunParams$truncation_param <- unbox(10)
json_data$RunParams$seed <- unbox(7050)
```


## Varying the matrix dimension
Storing the result
```{r}
test_size <- c(1000,2000,4000,8000,16000)
tested_SVDs <- c("rsi","ext_rsi","rbki","ext_rbki","exact")
```

```{r}
keys <- c("svd","size")

performance_metrics <- c("exe_time",
                   "reconstruction_err",
                   "singVal_err",
                   "l_singVects_err",
                   "r_singVects_err",
                   "l_singVects_angle",
                   "r_singVects_angle")

test_results <- 
   data.frame(matrix(nrow=0,ncol=length(c(keys,performance_metrics))))
names(test_results) <- c(keys, performance_metrics)

test_results[] <- lapply(test_results, function(x) numeric())
test_results$svd <- character()
```


Actual computation
```{r}
library(dplyr)
library(Matrix)

for(matSize in test_size){
  json_data$TestMatrix[[variable_dim]] <- unbox(matSize)

  cat("\nRows:", json_data$TestMatrix$rows,"\n")
  cat("Cols:", json_data$TestMatrix$cols,"\n")
  
  for(method in tested_SVDs){
    cat("SVD: ", method,"\n")
    #setting the method
    json_data$RunParams$method <- unbox(method)
    write_json(json_data, "params.json", pretty = TRUE)
    
    #computation
    system("/Users/marcogalliani/Desktop/fdaPDE-core/cmake-build-default/experiments/new_rsvd/new_rsvd")
    
    test_report <- read.csv(file="results/test_report.csv",header=F)
    
    #save results
    test_results <- test_results %>%
        add_row(svd=method, size=matSize)
    new_row <- test_results$svd==method & 
        test_results$size==matSize
    test_results[new_row, performance_metrics] <- unlist(test_report$V1)
      
  }
}
```

# Saving results
```{r}
write.csv(format(test_results, digits = 16),
          paste("past-runs",
                paste("RandSVD",
                      "-rows",params$rows,
                      "-cols",params$cols,
                      ".csv",sep=""),
          sep="/")
)
```