---
title: "Plotting the results"
params:
  n_cores: 1
  rows:
    value: "VAR"
    input: select
    choices: [1000,"VAR"]
  cols:
    value: 1000
    input: select
    choices: [1000,"VAR"]
---

## File
```{r}
file_name <- with(params, paste("RandSVD-replicated",
                                "-rows", params$rows,
                                "-cols", params$cols,
                                ".csv",sep=""))

if(params[["rows"]]=="VAR"){
  variable_dim <- "rows"
  fixed_dim <- "cols"
}else{
  variable_dim <- "cols"
  fixed_dim <- "rows"
}

library(readr)
test_results <- read_csv(paste("past-runs",file_name,sep="/"),
                         col_types = cols(...1 = col_skip()))

test_results[["svd"]] <- factor(test_results[["svd"]],
                                   levels = c("rsi","rbki","gen_rsi","gen_rbki","exact"))
```

```{r}
plot_dir <- "plots.rect/"
```


## Palette
```{r}
library(scales)
library(cowplot)
library(grid)
library(gridExtra) 
library(ggplot2)

color_map <- c(
  "rsi" = "#DF536B",
  "rbki" = "#61D04F",
  "gen_rsi" = "#2297E6",
  "gen_rbki" = "#28E2E5",
  "exact" = "#CD0BBC" 
)

dummy_plot <- 
  ggplot(data.frame(x = 1:length(color_map), y=1:length(color_map),
                  method=names(color_map)), 
       aes(x = x, y = y, color = method)) +
  geom_point(size = 5) +  # Use points just for the purpose of displaying the legend
  scale_color_manual(values = color_map) +  # Use the custom color mapping
  theme_void() +                            # Remove axes and background
  labs(color = "Method")


legend <- cowplot::get_legend(dummy_plot)
grid.newpage()
grid.draw(legend)

legend_grob <- grid.grabExpr(grid.draw(legend))

ggsave(paste(plot_dir,"legend-RandSVD-rectangular",
             ".pdf", sep=""), 
       legend_grob, width = 2, height = 2)
```
## Results

### Execution times
```{r}
source("../r-utils/plot_utils.R")

med.exe_time <- test_results %>%
  group_by(svd,size) %>%
  summarise(exe_time = median(exe_time))


exeTimes.plt <- grouped_lineplot(med.exe_time,
                 var_name.x = "size", 
                 var_name.y = "exe_time",
                 group_name = "svd", color_map,
                 log.x=T,log.y=T,
                 complexity.lines=c(1,2,3,4),
                 legend=T)


print(exeTimes.plt)

ggsave(paste(plot_dir,
             "exeTime",
             "-RandSVD",
             "-rows", params$rows,
             "-cols", params$cols,
             ".pdf", sep=""), 
       exeTimes.plt, width = 10, height = 5)
```

### Accuracy
```{r}
rand_test <- subset(test_results, svd!="exact")

rand_test.med_accuracy <- rand_test %>%
  group_by(svd,size) %>%
  summarise(
            reconstruction = median(reconstruction_err),
            eigVals = median(singVal_err),
            eigVects = median(eigVects_err)
            )

rand_test.med_accuracy$svd <- factor(rand_test.med_accuracy$svd,
                                     levels = c("rsi","rbki","nys_rsi","nys_rbki"))

rand_test.med_accuracy <- rand_test.med_accuracy[order(rand_test.med_accuracy$size,rand_test.med_accuracy$svd),]
```

Export table in latex
```{r}
library(kableExtra)

what_is <- rand_test.med_accuracy %>%
  kbl(caption="Accuracy analysis of randomized SVD algorithms on matrices with slow singular values decay",
      digits = 12,
      format="latex",
      col.names = names(rand_test.med_accuracy),
      align="r") %>%
  kable_minimal(full_width = F,  html_font = "Source Sans Pro")
```







