---
title: "Plotting the results"
---

## File
```{r}
file_name <- paste("RandSVD-squared-replicated",
                   ".csv",sep="")


library(readr)
test_results <- read_csv(paste("past-runs",file_name,sep="/"),
                         col_types = cols(...1 = col_skip()))

test_results[["svd"]] <- as.factor(test_results[["svd"]])
```

```{r}
plot_dir <- "plots.square/"
```


## Palette
```{r}
library(scales)
library(cowplot)
library(grid)
library(gridExtra) 
library(ggplot2)

col_palette <- palette.colors(n=6, palette = "R4")
color_map <- c(
  "rsi" = col_palette[2],
  "rbki" = col_palette[3],
  "gen_rsi" = col_palette[4],
  "gen_rbki" = col_palette[5],
  "exact" = col_palette[6]
)

dummy_plot <- 
  ggplot(data.frame(x = 1:length(color_map), y=1:length(color_map),
                  method=names(color_map)), 
       aes(x = x, y = y, color = method)) +
  geom_point(size = 5) +  # Use points just for the purpose of displaying the legend
  scale_color_manual(values = color_map) +  # Use the custom color mapping
  theme_void() +                            # Remove axes and background
  labs(color = "Method")


legend <- cowplot::get_legend(dummy_plot)
grid.newpage()
grid.draw(legend)

legend_grob <- grid.grabExpr(grid.draw(legend))

ggsave(paste(plot_dir,"legend-RandSVD-square",
             ".pdf", sep=""), 
       legend_grob, width = 2, height = 2)
```
## Results

### Execution times
```{r}
source("../r-utils/plot_utils.R")

med.exe_time <- test_results %>%
  group_by(svd,size) %>%
  summarise(exe_time = median(exe_time))


exeTimes.plt <- grouped_lineplot(med.exe_time,
                 var_name.x = "size", 
                 var_name.y = "exe_time",
                 group_name = "svd", color_map,
                 log.x=T,log.y=T,
                 complexity.lines=c(1,2,3,4),
                 legend=T)

print(exeTimes.plt)

ggsave(paste(plot_dir,
             "exeTime",
             "-RandSVD-square",
             ".pdf", sep=""), 
       exeTimes.plt, width = 10, height = 5)
```


### Accuracy
```{r}
rand_test <- subset(test_results, svd!="exact")

rand_test.med_accuracy <- rand_test %>%
  group_by(svd,size) %>%
  summarise(
            reconstruction_err = median(reconstruction_err),
            singVal_err = median(singVal_err),
            l_singVects_err = median(l_singVects_err),
            r_singVects_err = median(r_singVects_err)
            )

rand_test.med_accuracy$svd <- factor(rand_test.med_accuracy$svd,
                                     levels = c("rsi","rbki","gen_rsi","gen_rbki"))

rand_test.med_accuracy <- rand_test.med_accuracy[order(rand_test.med_accuracy$size,rand_test.med_accuracy$svd),]
```

Export table in latex
```{r}
library(kableExtra)

what_is <- rand_test.med_accuracy %>%
  kbl(caption="Accuracy analysis of randomized SVD algorithms on matrices with slow singular values decay",
      digits = 12,
      format="latex",
      col.names = c("svd","size","reconstruction","singVals","l_singVects","r_singVects"),
      align="r") %>%
  kable_minimal(full_width = F,  html_font = "Source Sans Pro")
```

```{r}

```



#### Old plots
```{r}
singVal_err.plot <- grouped_boxplot(rand_test,
                 "Singular value error",
                 var_name.x = "size", 
                 var_name.y = "singVal_err",
                 group_name = "svd", color_map,
                 log.y = T
                 ) 
print(singVal_err.plot)

ggsave(paste(plot_dir,
             "singVal_err",
             "-RandSVD",
             "-rows", params$rows,
             "-cols", params$cols,
             ".pdf", sep=""), 
       singVal_err.plot, width = 10, height = 5)
```

```{r}
rec_err.plot <- grouped_boxplot(rand_test,
                 "Reconstruction error",
                 "size", "reconstruction_err",
                 group_name = "svd", color_map,
                 log.y = T
                 ) 

print(rec_err.plot)

ggsave(paste(plot_dir,
             "reconstruction_err",
             "-RandSVD",
             "-rows", params$rows,
             "-cols", params$cols,
             ".pdf", sep=""), 
       rec_err.plot, width = 10, height = 5)
```

```{r}
l_singVect_err.plot <- grouped_boxplot(rand_test,
                 "Error on the left singular vectors",
                 "size", "l_singVects_err",
                 group_name = "svd", color_map,
                 log.y = T
                 ) 

print(l_singVect_err.plot)

ggsave(paste(plot_dir,
             "l_singVects_err",
             "-RandSVD",
             "-rows", params$rows,
             "-cols", params$cols,
             ".pdf", sep=""), 
       l_singVect_err.plot, width = 10, height = 5)

```

```{r}
r_singVect_err.plot <- grouped_boxplot(rand_test,
                 "Error on the right singular vectors",
                 "size", "r_singVects_err",
                 group_name = "svd", color_map,
                 log.y = T
                 ) 

print(r_singVect_err.plot)

ggsave(paste(plot_dir,
             "r_singVects_err",
             "-RandSVD",
             "-rows", params$rows,
             "-cols", params$cols,
             ".pdf", sep=""), 
       r_singVect_err.plot, width = 10, height = 5)
```

```{r}
l_subspace_err.plot <- grouped_boxplot(rand_test,
                 "Left singular subspace error",
                 "size", "l_singVects_angle",
                 group_name = "svd", color_map,
                 log.y = T
                 ) 

print(l_subspace_err.plot)

ggsave(paste(plot_dir,
             "l_singSubspace_err",
             "-RandSVD",
             "-rows", params$rows,
             "-cols", params$cols,
             ".pdf", sep=""), 
       l_subspace_err.plot, width = 10, height = 5)
```
```{r}
r_subspace_err.plot <- grouped_boxplot(rand_test,
                 "Right singular subspace error",
                 "size", "r_singVects_angle",
                 group_name = "svd", color_map,
                 log.y = T
                 ) 

print(r_subspace_err.plot)

ggsave(paste(plot_dir,
             "r_singSubspace_err",
             "-RandSVD",
             "-rows", params$rows,
             "-cols", params$cols,
             ".pdf", sep=""), 
       r_subspace_err.plot, width = 10, height = 5)
```






