---
title: "REVD comparison"
---

```{r}
test_results <- read.csv("results/randEVD_comparison.csv",
                         header = T)
test_results$size <- as.factor(test_results$size)
```

## Legend

```{r}
source("../r-utils/plot_utils.R")

library(scales)
library(cowplot)
library(grid)
library(gridExtra) 

col_palette <- palette.colors(n=7, palette = "R4")[2:7]
color_map <- c(
  "scikit-learn" = "darkblue",
  "rsi" = "#DF536B",
  "rbki" = "#61D04F",
  "nys_rsi" = "#F5C710",
  "nys_rbki" = "#A020F0"
)

show_col(color_map)

dummy_plot <- 
  ggplot(data.frame(x = 1:length(color_map), y=1:length(color_map),
                  method=names(color_map)), 
       aes(x = x, y = y, color = method)) +
  geom_point(size = 5) +  # Use points just for the purpose of displaying the legend
  scale_color_manual(values = color_map) +  # Use the custom color mapping
  theme_void() +                            # Remove axes and background
  labs(color = "SVD") +
  guides(color=guide_legend(ncol=2))



legend <- cowplot::get_legend(dummy_plot)
grid.newpage()
grid.draw(legend)

legend_grob <- grid.grabExpr(grid.draw(legend))

ggsave(paste("plots/legend-REVD-VS-scikit",
             ".pdf", sep=""), 
       legend_grob, width = 2, height = 2)

```

## Metrics
```{r}
slow_test <- subset(test_results,decay=="slow")
slow_test <- subset(slow_test,svd!="exact")
```


### Times
```{r}
exe_time.plot <- grouped_lineplot(slow_test,
                 title = "Execution time [s]",
                 "size", "execution_time",
                 group_name = "svd", color_map,
                 log.x = T, log.y = T,
                 legend = F
                 ) 

print(exe_time.plot)

ggsave(paste("plots/",
             "exe_time",
             "-REVD",
             ".pdf", sep=""), 
       exe_time.plot, width = 10, height = 5)
```


### Accuracy

```{r}
eig_val_err.plot <- grouped_lineplot(slow_test,
                 title = "Eigenvalues error",
                 "size", "eig_val_error",
                 group_name = "svd", color_map,
                 log.x = F, log.y = T, legend = F
                 ) 

print(eig_val_err.plot)

ggsave(paste("plots/",
             "eig_val_err",
             "-REVD",
             ".pdf", sep=""), 
       eig_val_err.plot, width = 10, height = 5)
```

```{r}
eig_vect_err.plot <- grouped_lineplot(slow_test,
                 title = "Eigenvector error",
                 "size", "eig_vect_error",
                 group_name = "svd", color_map,
                 log.y = T, legend = F
                 ) 

print(eig_vect_err.plot)

ggsave(paste("plots/",
             "eig_vect_err",
             "-REVD",
             ".pdf", sep=""), 
       eig_vect_err.plot, width = 10, height = 5)
```

## Decay
```{r}
decay_list <- list(
  fast = function(x) 0.95^x,
  slow = function(x) 1/log(1+x)
)

col_palette <- palette.colors(n=3, palette = "R4")[2:3]
show_col(col_palette)

# Create a data frame to map function names
function_data <- data.frame(
  decay = names(decay_list)
)

# Plot
decay.plot <- ggplot(data = function_data, aes(color = decay)) +
  theme_light() +
  xlim(1, 1000) +
  stat_function(data = subset(function_data, decay == "slow"), fun = decay_list$slow) +
  stat_function(data = subset(function_data, decay == "fast"), fun = decay_list$fast) +
  labs(x = "index", y = "singular values", color = "decay") +
  scale_color_manual(values = c("slow" = col_palette[1], "fast" = col_palette[2])) 

print(decay.plot)

ggsave(paste("plots/",
             "singularVal-decay",
             ".pdf", sep=""), 
       decay.plot, width = 5, height = 2)
```

