---
title: "REVD comparison"
---

```{r}
test_results <- read.csv("results/randSVD_comparison.csv",
                         header = T)
test_results$size <- as.factor(test_results$size)
```

## Legend

```{r}
source("../r-utils/plot_utils.R")

library(scales)
library(cowplot)
library(grid)
library(gridExtra) 

col_palette <- palette.colors(n=5, palette = "R4")
color_map <- c(
  "scikit-learn" = col_palette[2],
  "rsi" = col_palette[3],
  "rbki" = col_palette[4]
)

show_col(color_map)

dummy_plot <- 
  ggplot(data.frame(x = 1:length(color_map), y=1:length(color_map),
                  method=names(color_map)), 
       aes(x = x, y = y, color = method)) +
  geom_point(size = 5) +  # Use points just for the purpose of displaying the legend
  scale_color_manual(values = color_map) +  # Use the custom color mapping
  theme_void() +                            # Remove axes and background
  labs(color = "SVD") +
  guides()



legend <- cowplot::get_legend(dummy_plot)
grid.newpage()
grid.draw(legend)

legend_grob <- grid.grabExpr(grid.draw(legend))

ggsave(paste("plots/legend-RSVD-VS-scikit",
             ".pdf", sep=""), 
       legend_grob, width = 2, height = 2)

```

## Metrics
### Times
```{r}
exe_time.plot <- grouped_lineplot(test_results,
                 "Execution time [s]",
                 "size", "execution_time",
                 group_name = "svd", color_map,
                 log.y = T
                 )

print(exe_time.plot)

ggsave(paste("plots/",
             "exe_time",
             "-RSVD",
             ".pdf", sep=""), 
       exe_time.plot, width = 10, height = 5)
```


### Accuracy
```{r}
rec_err.plot <- grouped_lineplot(test_results,
                 "Reconstruction error",
                 "size", "rec_error",
                 group_name = "svd", color_map,
                 log.y = T
                 ) 

print(rec_err.plot)

ggsave(paste("plots/",
             "reconstruction_err",
             "-RSVD",
             ".pdf", sep=""), 
       rec_err.plot, width = 10, height = 5)
```

```{r}
sing_val_err.plot <- grouped_lineplot(test_results,
                 "Singular values error",
                 "size", "sing_val_error",
                 group_name = "svd", color_map,
                 log.y = T
                 ) 

print(sing_val_err.plot)

ggsave(paste("plots/",
             "eig_val_err",
             "-RSVD",
             ".pdf", sep=""), 
       sing_val_err.plot, width = 10, height = 5)
```

```{r}
l_sing_vect_err.plot <- grouped_lineplot(test_results,
                 "Singular vectors error",
                 "size", "l_sing_vect_error",
                 group_name = "svd", color_map,
                 log.y = T
                 ) 

print(l_sing_vect_err.plot)

ggsave(paste("plots/",
             "l_sing_vect_err",
             "-RSVD",
             ".pdf", sep=""), 
       l_sing_vect_err.plot, width = 10, height = 5)
```

```{r}
r_sing_vect_err.plot <- grouped_lineplot(test_results,
                 "Singular vectors error",
                 "size", "r_sing_vect_error",
                 group_name = "svd", color_map,
                 log.y = T
                 ) 

print(r_sing_vect_err.plot)

ggsave(paste("plots/",
             "r_sing_vect_err",
             "-RSVD",
             ".pdf", sep=""), 
       r_sing_vect_err.plot, width = 10, height = 5)
```



